### ISSUE TITLE
AES-256? 

### ISSUE THREAD

**Issue by nathanawmk** [Microsoft/PQCrypto-SIDH#10]
Hello! Wondering if including AES-256 is in the security level roadmap? 

Nathan Aw

**Comment by OverclockedSanic** [comment]
Seems useless. The point of SIDH/SIKE is to establish a key for _any_ symmetric encryption algorithm (see [Diffie-Hellman key exchange](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange)), be it AES, ChaCha20, TwoFish, etc... The symmetric encryption algorithm should be chosen or implemented by the programmer, not by this library.

**Comment by OverclockedSanic** [comment]
I did however find that SIKEp964 was also submitted to NIST, offering stronger security, code available here: [https://github.com/dconnolly/NIST-PQC-SIKE](https://github.com/dconnolly/NIST-PQC-SIKE/tree/master/Reference_Implementation)

**Comment by patricklonga** [comment]
There are no plans to include P964 for now. P751 already offers plenty of security for the foreseeable future (unless there is a breakthrough in cryptanalysis).

**Comment by mouse07410** [comment]
@patricklonga I'd appreciate if your reconsidered: several applications are not satisfied by symmetric strength equivalent of AES-192, and insist on AES-256 equivalent (for example, see the follow-up to Suite B). 

Since P964 seems already included in the NIST submission - what is the problem adding it here, as people (including myself) explicitly ask for it?

Besides, AES-192 has about 96 bits of strength against Grover, while AES-256 provides 128 bits.
